version: '3.3'

services:

  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - reddit_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    build: ../src/ui/docker_build.sh
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${INNER_UI_PORT}:${OUTER_UI_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.ui
        fluentd-async: 'true'
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    build: ../src/post-py/docker_build.sh
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.post
        fluentd-async: 'true'
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    build: ../src/comment/docker_build.sh
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.comment
        fluentd-async: 'true'
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net
  
  node-exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    environment:
      - MONGODB_URI=mongodb://post_db:27017
    ports:
      - '9216:9216'
    networks:
      - back_net

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - '9115:9115'
    networks:
      - back_net
      - front_net

volumes:
  reddit_db:
  prometheus_data:

networks:
  back_net:
  front_net:
