version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - reddit_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    volumes:
      - reddit_ui:/app
    ports:
      - ${INNER_UI_PORT}:${OUTER_UI_PORT}/tcp
    networks:
      - front_net
    command: puma --debug -w 2
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    volumes:
      - reddit_post:/app
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    volumes:
      - reddit_comment:/app
    networks:
      - back_net
      - front_net
    command: puma --debug -w 2

volumes:
  reddit_db:
  reddit_pos:
  reddit_comment:
  reddit_ui:

networks:
  back_net:
  front_net:
